title: Jayson Tian
email: jaysontian444@gmail.com

description: >-
  I spend most of my time thinking about the death and regeneration of my neurons. 
  Aside from that, I'm either playing volleyball, drawing digitally, coding, or 
  helping out in educational initiatives.
baseurl: ""
url: "http://jaysontian.com"
twitter_username: jekyllrb
github_username:  jekyll

sass:
  sass_dir: _sass
include: ['_pages']

kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed

collections:
  articles:
    output: true
    permalink: /blog/:name

defaults:
- scope:
    type: articles
  values:
    layout: article

